{
	"version": 1555023663,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/block.png",
		"images/emoji-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/tiledbackground8.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/tiledbackground9.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/tiledbackground10.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"media/fade.m4a",
		"media/fade.ogg",
		"media/invincible.m4a",
		"media/invincible.ogg",
		"media/sad background music - no copyright - free to use.m4a",
		"media/sad background music - no copyright - free to use.ogg",
		"media/punch sound effect.m4a",
		"media/punch sound effect.ogg",
		"media/cartoon jump sound effect.m4a",
		"media/cartoon jump sound effect.ogg",
		"media/elektronomia.m4a",
		"media/elektronomia.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"Amazon-Web-App-API.min.js",
		"Amazon-Web-App-API-tester.min.js",
		"tizen-iap.js",
		"cws-buy.js",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js",
		"cordova.oauth2.js"
	]
}